#!/usr/bin/env python3
"""Generate browser-side aliases for Docsify root-level legacy routes.

Docsify links inside nested Markdown files should be relative to the current
file/directory. The site enables `relativePath: true`, but older links that were
already shared as `#/SomeArticle` still need a safe compatibility redirect when
`SomeArticle.md` actually lives below a category directory.
"""
from __future__ import annotations

from collections import defaultdict
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
OUT = DOCS / "route-aliases.js"


def route_for_md(path: Path) -> str:
    rel = path.relative_to(DOCS)
    if rel.name.upper() == "README.MD":
        parent = rel.parent
        if str(parent) == ".":
            return "/"
        return "/" + parent.as_posix()
    return "/" + rel.with_suffix("").as_posix()


def collect_aliases() -> dict[str, str]:
    buckets: dict[str, set[str]] = defaultdict(set)

    for md in sorted(DOCS.rglob("*.md")):
        rel = md.relative_to(DOCS)
        target = route_for_md(md)

        # Do not alias root-level docs to themselves.
        if len(rel.parts) <= 1:
            continue

        if rel.name.upper() == "README.MD":
            key_slug = rel.parent.name
        else:
            key_slug = rel.stem

        if not key_slug:
            continue

        buckets[f"/{key_slug}"].add(target)

    # Only generate unambiguous aliases. If two files share the same basename,
    # leaving the route unresolved is safer than redirecting to the wrong page.
    return {
        key: sorted(targets)[0]
        for key, targets in sorted(buckets.items())
        if len(targets) == 1 and key != sorted(targets)[0]
    }


def main() -> None:
    aliases = collect_aliases()
    body = json.dumps(aliases, ensure_ascii=False, indent=2, sort_keys=True)
    OUT.write_text(
        "/* Auto-generated by scripts/generate-route-aliases.py. Do not edit manually. */\n"
        "(function () {\n"
        "  'use strict';\n\n"
        f"  var routeAliases = {body};\n\n"
        "  function currentRoute() {\n"
        "    var hash = window.location.hash || '';\n"
        "    if (!hash || hash === '#') return '/';\n\n"
        "    var raw = hash.slice(1);\n"
        "    var queryIndex = raw.indexOf('?');\n"
        "    var path = queryIndex >= 0 ? raw.slice(0, queryIndex) : raw;\n\n"
        "    try { path = decodeURIComponent(path); } catch (e) {}\n"
        "    if (!path) path = '/';\n"
        "    if (path.charAt(0) !== '/') path = '/' + path;\n\n"
        "    path = path.replace(/\\.md$/i, '').replace(/\\/README$/i, '/');\n"
        "    if (path.length > 1) path = path.replace(/\\/+$/g, '');\n"
        "    return path || '/';\n"
        "  }\n\n"
        "  function redirectIfAliased() {\n"
        "    var route = currentRoute();\n"
        "    var target = routeAliases[route];\n"
        "    if (!target || target === route) return;\n\n"
        "    var raw = (window.location.hash || '#').slice(1);\n"
        "    var queryIndex = raw.indexOf('?');\n"
        "    var suffix = queryIndex >= 0 ? raw.slice(queryIndex) : '';\n"
        "    window.location.replace(window.location.pathname + window.location.search + '#' + target + suffix);\n"
        "  }\n\n"
        "  window.__KB_ROUTE_ALIASES__ = routeAliases;\n"
        "  redirectIfAliased();\n"
        "  window.addEventListener('hashchange', redirectIfAliased);\n"
        "})();\n",
        encoding="utf-8",
    )
    print(f"Generated {len(aliases)} route aliases -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
